# -*- coding: utf-8 -*-
"""Mi Primera Aplicacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBT5pKWCCTqI9aBDdMLISlMq4hl85C0J
"""

# Importamos las Librerias
import streamli as st
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# Install streamlit
# %pip install streamlit

# Importamos las Librerias
import streamlit as st
import pandas as pd

st.title("Mi Primera App con Streamlit")